import type { UiLocale } from "@/lib/quest-agent/types";

const en = {
  metadata: {
    title: "Quest Agent v0.6",
    description: "Keep one clear focus, detect drift early, and return without shame.",
  },
  nav: {
    portfolio: "Portfolio",
    intake: "Intake",
    map: "Map",
    today: "Today",
    returnFlow: "Return",
    review: "Review",
  },
  shell: {
    kicker: "Quest Agent v0.6",
    title: "Keep moving, and make returning cheaper when you stall.",
    description: "One focus goal, a clear today plan, and a gentle return loop when momentum drops.",
    mirror: "Current state",
    focus: "Focus",
    nextRestart: "Next restart",
    portfolioHealth: "Portfolio health",
    healthTitle: "Choose the work, notice drift, then return in 15 minutes.",
    activeGoals: "Active goals",
    mainToday: "Main today",
    switchDensity: "Switches",
    activeGoalsPill: "Active",
    localeLabel: "Language",
    environment: "Environment",
    languageJa: "Japanese",
    languageEn: "English",
  },
  common: {
    openPortfolio: "Open Portfolio",
    openToday: "Open Today",
    openReturn: "Open Return",
    openMap: "Open Map",
    cancel: "Cancel",
    minutes: "min",
    durationMinutes: "{value}m",
    durationHours: "{value}h",
    running: "running",
    noSummary: "No summary yet.",
    noData: "No data yet.",
    backToToday: "Back to Today",
    showDetails: "Show details",
    hideDetails: "Hide details",
    itemCount: "{value} items",
  },
  today: {
    title: "Set up today lightly, then return quickly if work drifts.",
    lead: "Session Start stays light, Mirror stays factual, and Return opens only when it helps.",
    noFocusTitle: "No focus goal is selected.",
    noFocusBody: "Choose one focus goal in Portfolio before shrinking today into a small block.",
    noRouteTitle: "This focus goal needs a route first.",
    noRouteBody: "Create the route first so today can shrink into 1 to 3 concrete steps.",
    replanAi: "Replan with AI",
    replanHeuristic: "Replan heuristically",
    openReturnHint: "Use Return when improve or other work keeps stacking up before main work starts.",
    mirrorTitle: "Current state",
    sessionStartTitle: "Session Start",
    sessionStartLead: "Decide the connection, artifact, timebox, and end condition before you begin.",
    activeSessionTitle: "Active session",
    activeSessionEmpty: "Use Session Start to choose the category and end condition before you begin.",
    todayPlanTitle: "Today plan",
    sessionsTitle: "Today sessions",
    sessionsEmpty: "The first finished block becomes the baseline for main ratio and start delay.",
    blockerTitle: "Blocker intake",
    blockerLead: "Name the stall without blame.",
    fallbackTheme: "Use the clearest visible quest first and keep drift small enough to notice.",
    fallbackNotes: {
      capacity: "Today's capacity: {value}",
      noCapacity: "Start with one timeboxed session.",
      hasSession: "Finish the current session before starting another one.",
      needsSessionStart: "Session Start runs the gate before work begins.",
    },
    stats: {
      readyQuests: "Ready quests",
      activeSession: "Active session",
      mainToday: "Main today",
      metaToday: "Meta today",
      switchDensity: "Switch density",
      returnState: "Return",
    },
    details: {
      readyQuests: "The easiest quests to move today",
      noSession: "No session running",
      mainToday: "Main session time today",
      metaToday: "Avoidant improve / other",
      switchDensity: "Goal + category changes",
      returnOpen: "Open",
      returnClear: "Clear",
    },
    fields: {
      category: "Category",
      quest: "Quest",
      mainConnection: "Connection to main work",
      timebox: "Time limit",
      artifact: "What will leave this session?",
      artifactPlaceholder: "A note, sent message, decision, PR, or other visible output",
      doneWhen: "Stop when",
      doneWhenPlaceholder: "What makes this block done?",
      artifactLeft: "Artifact actually left",
      artifactLeftPlaceholder: "Optional, but it helps the next restart.",
      blockerTitle: "What is stuck?",
      blockerQuest: "Related quest",
      blockerDescription: "Description",
      blockerType: "Type",
      blockerSeverity: "Severity",
    },
    buttons: {
      runGate: "Run gate",
      confirmStart: "Start this session",
      openReturnInstead: "Open Return instead",
      finishSession: "Finish session",
      recordBlocker: "Record blocker",
    },
    messages: {
      planAi: "AI refreshed today's route.",
      planHeuristic: "Heuristic mode refreshed today's route.",
      gateClear: "Gate checked. You can begin now.",
      gateRisk: "The gate sees some drift risk. You can open Return first or confirm anyway.",
      sessionStartedBuild: "Session started.",
      sessionStartedAvoidant: "Session started. You can still open Return if needed.",
      sessionFinished: "Work session finished.",
      blockerSaved: "Blocker recorded. The reroute hint is ready.",
    },
    errors: {
      replan: "Failed to refresh today's plan.",
      startSession: "Failed to start session.",
      gate: "Gate check failed.",
      finishSession: "Failed to finish session.",
      blockerSave: "Failed to save blocker.",
    },
    labels: {
      doneWhen: "Done when",
      timebox: "Timebox",
      artifactLeft: "Artifact left",
    },
  },
  portfolio: {
    title: "Keep one front goal clear and keep parallel work honest.",
    lead: "One focus goal stays in front, the active limit stays real, and parked work keeps a clean restart note.",
    addGoal: "Add goal",
    focusTitle: "Current focus",
    focusEmpty: "No focus goal selected",
    focusBody: "Choose one goal to stay front-and-center this week.",
    settingsTitle: "Settings",
    activeTitle: "Active",
    activeEmpty: "No active goals yet.",
    backlogTitle: "Backlog",
    backlogEmpty: "No backlog goals right now.",
    parkedTitle: "Parked",
    parkedEmpty: "No parked goals right now.",
    resumeQueueTitle: "Resume queue",
    resumeQueueEmpty: "When you park a goal, its restart conditions appear here.",
    defaults: {
      switchReason: "This deserves the front slot this week.",
      resumeReason: "The restart trigger is now clear.",
      focusFallback: "This goal now matters most.",
      resumeFallback: "The restart trigger is now clear.",
    },
    stats: {
      focusGoal: "Focus goal",
      activeGoals: "Active goals",
      resumeQueue: "Resume queue",
      switches: "Switches",
      medianResume: "Median resume",
      reviewRate: "Review rate",
    },
    details: {
      currentActiveCount: "Current active count",
      resumeQueue: "Goals parked with restart notes",
      recordedThisWeek: "Recorded this week",
      restartDelay: "Delay until restart",
      last4Weeks: "Last 4 weeks",
    },
    fields: {
      activeGoalLimit: "Active goal limit",
      switchReason: "Why move this to the front now?",
      switchReasonPlaceholder: "Why should this become the focus now?",
      resumeReason: "Why is this ready to restart?",
      resumeReasonPlaceholder: "Why can this restart now?",
      stopMode: "Stop mode",
      resumeTrigger: "Resume trigger",
      whyStopNow: "Why stop now?",
      parkingNote: "Parking note",
      parkingNotePlaceholder: "Where did you stop and what remains?",
      nextRestartStep: "Next restart step",
      triggerDetail: "Trigger detail",
      triggerPlaceholder: "When should this come back?",
    },
    buttons: {
      saveLimit: "Save limit",
      editRoute: "Open route",
      startIntake: "Start intake",
      setFocus: "Set focus",
      activateAndFocus: "Activate + Focus",
      parkGoal: "Park goal",
      resumeGoal: "Resume goal",
      saveParkingNote: "Save parking note",
    },
    queue: {
      missingGoal: "Missing goal",
      parkedAgo: "Parked {days} day(s) ago",
      whyStopped: "Why stopped",
      nextRestart: "Next restart step",
      trigger: "Trigger",
    },
    messages: {
      limitSaved: "Active goal limit updated.",
      focusSaved: "Focus goal updated.",
      resumeSaved: "Goal resumed and moved back toward focus.",
      parkedSaved: "Goal moved into the resume queue with a restart note.",
    },
    errors: {
      limitSave: "Failed to update active goal limit.",
      focusSave: "Failed to change focus goal.",
      resumeSave: "Failed to resume goal.",
      parkSave: "Failed to park goal.",
    },
  },
  review: {
    title: "Review how easy it is to come back by looking at ratios and delays.",
    lead: "v0.6 keeps the switching review and adds main ratio, meta ratio, start delay, resume delay, switch density, and if-then coverage.",
    noGoalTitle: "You need at least one goal before you can review the portfolio.",
    addGoal: "Add goal",
    formTitle: "Review form",
    dailyLeadTitle: "Daily lead metrics",
    dailyLeadEmpty: "Daily metrics appear after work sessions and return runs are recorded.",
    focusCandidatesTitle: "Next focus candidates",
    focusCandidatesLead: "Which goal should get the front slot next?",
    savedReviewsTitle: "Saved reviews",
    savedReviewsEmpty: "The first review becomes the baseline for future comparisons.",
    stats: {
      mainRatio: "Main ratio",
      metaRatio: "Meta ratio",
      startDelay: "Start delay",
      resumeDelay: "Resume delay",
      switchDensity: "Switch density",
      ifThen: "If-then coverage",
    },
    details: {
      mainRatio: "Main session time / tracked time",
      metaRatio: "Avoidant improve / other",
      startDelay: "First session to first main",
      resumeDelay: "Parked to resumed",
      switchDensity: "Goal + category changes",
      ifThen: "Return runs with if-then",
    },
    fields: {
      periodStart: "Period start",
      periodEnd: "Period end",
      summary: "Progress summary",
      learnings: "Switching / resumption learnings",
      rerouteNote: "Reroute note",
      nextFocus: "Next focus",
    },
    buttons: {
      saveReview: "Save weekly review",
      setFocus: "Set focus",
    },
    messages: {
      saved: "Review saved.",
      focusSaved: "Focus goal updated from review.",
      focusReason: "Review selected the next focus goal.",
    },
    errors: {
      save: "Review save failed.",
      focusSave: "Failed to set focus goal from review.",
    },
    labels: {
      startDelay: "Start delay",
      resumeDelay: "Resume delay",
      switchDensity: "Switch density",
      ifThenCoverage: "If-then coverage",
      learnings: "Learnings",
      reroute: "Reroute",
      nextFocus: "Next focus",
    },
    candidateReason: "This looks easy to organize as a front-slot candidate this week.",
  },
  returnFlow: {
    title: "Notice the drift, diagnose it once, then choose the next 15 minutes.",
    lead: "Move through Mirror, COM-B, WOOP / if-then, and the decision in one calm page.",
    noFocusTitle: "No focus goal is selected.",
    noFocusBody: "Pick a focus goal in Portfolio before using Return.",
    combTitle: "Name the main bottleneck",
    planTitle: "Build the return plan",
    decisionTitle: "Choose what this means",
    latestTitle: "Latest return",
    steps: {
      facts: "See the facts",
      bottleneck: "Name the bottleneck",
      plan: "Build the return plan",
      decision: "Choose this time",
    },
    stepState: {
      current: "Current",
      complete: "Done",
      upcoming: "Next",
    },
    stepHelp: {
      facts: "Look at the facts first. No self-judgment.",
      bottleneck: "Choose the main drag and define the smallest visible win.",
      plan: "Write WOOP, optional if-then, and the next 15-minute move.",
      decision: "Decide whether to keep going, detour, hold, or retreat.",
    },
    summaryLabels: {
      facts: "Mirror",
      bottleneck: "Smallest win",
      plan: "Next 15m",
      decision: "Decision",
    },
    fields: {
      mainQuest: "Main quest",
      quest: "Related quest",
      primaryBottleneck: "Primary bottleneck",
      diagnosisType: "Diagnosis type",
      avoidanceHypothesis: "Avoidance hypothesis",
      smallestWin: "Smallest visible win",
      woopPlan: "WOOP",
      woopPlaceholder: "Wish / Outcome / Obstacle / Plan",
      ifThenPlan: "If-then",
      ifThenPlaceholder: "If X happens, then I will do Y.",
      next15mAction: "Next 15-minute action",
      next15mPlaceholder: "What is the next small move?",
      decision: "Decision",
      reviewDate: "Review date",
      decisionNote: "Decision note",
      reason: "Reason",
      parkingNote: "Parking note",
      nextRestartStep: "Next restart step",
      resumeTriggerType: "Resume trigger type",
      resumeTriggerText: "Resume trigger",
    },
    buttons: {
      back: "Back",
      next: "Next",
      save: "Save return flow",
    },
    messages: {
      saved: "Return flow saved.",
    },
    errors: {
      save: "Failed to save return flow.",
    },
    labels: {
      next15m: "Next 15m",
      ifThen: "If-then",
    },
  },
  intake: {
    page: "Intake",
    titleNew: "Add a goal without breaking the portfolio balance.",
    titleEdit: "Shape the goal into something you can actually move.",
    lead: "Capture the goal cleanly first, then turn it into something you can move.",
    refineAi: "Refine with AI",
    refineHeuristic: "Refine with heuristics",
    saveGoal: "Save goal",
    stats: {
      focus: "Focus goal",
      active: "Active goals",
      resume: "Resume queue",
      momentum: "Momentum",
    },
    details: {
      noFocus: "No focus selected",
      active: "Current active count",
      resume: "Goals parked with restart notes",
      momentum: "Completed quests in the last 7 days",
    },
    formTitle: "Goal form",
    formLeadNew: "Capture a new goal",
    formLeadEdit: "Minimum input is enough",
    draftTitle: "Agent draft",
    draftLead: "What the agent sees",
    fields: {
      title: "Goal title",
      description: "Goal summary",
      why: "Why",
      deadline: "Deadline",
      successCriteria: "Success criteria",
      successCriteriaPlaceholder: "One line per item",
      currentState: "Current state",
      constraints: "Constraints",
      constraintsPlaceholder: "One line per item",
      concerns: "Concerns / likely blockers",
      todayCapacity: "Today's capacity",
      todayCapacityPlaceholder: "How much can you realistically do today?",
    },
    draftLabels: {
      mode: "Mode",
      summary: "Goal summary",
      success: "Success criteria",
      questions: "Open questions",
      route: "First route note",
    },
    messages: {
      refinedAi: "AI drafted a sharper goal.",
      refinedHeuristic: "Heuristic mode drafted a sharper goal.",
      savedActive: "Goal saved. Next, turn it into a route on Quest Map.",
      savedBacklog: "Goal saved to the portfolio backlog. Activate it from Portfolio when a slot opens.",
      emptyDraft: "Use the refine button to turn a vague goal into a cleaner working draft.",
    },
    errors: {
      refine: "Intake refinement failed.",
      save: "Goal save failed.",
    },
  },
  map: {
    page: "Quest Map",
    noFocusTitle: "Select a focus goal first.",
    noFocusBody: "Each route belongs to one focus goal, so pick the goal that should stay in front before editing the map.",
    openPortfolio: "Open Portfolio",
    heroTitle: "Break the focus goal into resumable stages and quests.",
    lead: "The map is not a giant plan. It is a route you can restart. Keep milestones and quests small so today stays easy to choose.",
    generateAi: "Generate draft with AI",
    generateHeuristic: "Generate draft heuristically",
    saveRoute: "Save route",
    storedRoute: "Stored route",
    storedLead: "The route attached to the current focus goal",
    draftTitle: "Editable draft",
    draftLead: "Tune wording and scope before saving",
    emptyStored: "No saved route yet. Generate a draft first.",
    emptyDraft: "Generate a draft to edit milestones and quests here.",
    messages: {
      generatedAi: "AI drafted a route.",
      generatedHeuristic: "Heuristic mode drafted a route.",
      saved: "Route saved. Next, decide today's route.",
    },
    errors: {
      generate: "Quest Map generation failed.",
      save: "Failed to save Quest Map.",
    },
    fields: {
      routeSummary: "Route summary",
      milestoneTitle: "Milestone title",
      targetDate: "Target date",
      description: "Description",
      questTitle: "Quest title",
      priority: "Priority",
      type: "Type",
      minutes: "Minutes",
      dueDate: "Due date",
    },
    milestoneLabel: "Milestone",
  },
} as const;

const ja = {
  metadata: {
    title: "Quest Agent v0.6",
    description: "メインクエストを一つに絞り、ズレに早く気づき、責めずに戻せるようにする。",
  },
  nav: {
    portfolio: "ポートフォリオ",
    intake: "受け取り",
    map: "進め方",
    today: "今日",
    returnFlow: "戻し方",
    review: "ふり返り",
  },
  shell: {
    kicker: "Quest Agent v0.6",
    title: "進めつつ、止まったときの戻りコストを下げる",
    description: "メインクエストを一つに絞り、今日を軽く決め、勢いが落ちたら短く戻る。",
    mirror: "いまの状況",
    focus: "メインクエスト",
    nextRestart: "次の再開",
    portfolioHealth: "ポートフォリオ",
    healthTitle: "何を進めるか決め、ズレに気づいたら 15 分で戻る。",
    activeGoals: "同時進行中",
    mainToday: "今日のメインクエスト",
    switchDensity: "切替",
    activeGoalsPill: "進行中",
    localeLabel: "表示言語",
    environment: "環境",
    languageJa: "日本語",
    languageEn: "English",
  },
  common: {
    openPortfolio: "ポートフォリオを開く",
    openToday: "今日を開く",
    openReturn: "戻し方を開く",
    openMap: "進め方を開く",
    cancel: "キャンセル",
    minutes: "分",
    durationMinutes: "{value}分",
    durationHours: "{value}時間",
    running: "進行中",
    noSummary: "まだ概要がありません。",
    noData: "まだデータがありません。",
    backToToday: "今日に戻る",
    showDetails: "詳しく見る",
    hideDetails: "閉じる",
    itemCount: "{value}件",
  },
  today: {
    title: "今日を軽く決め、ズレたら短く戻る",
    lead: "Session Start は軽く、いまの状況は事実だけ、戻し方は必要な時だけ使う。",
    noFocusTitle: "まだメインクエストが選ばれていません。",
    noFocusBody: "まずはポートフォリオでメインクエストを一つ選んでください。",
    noRouteTitle: "このメインクエストにはまだ進め方がありません。",
    noRouteBody: "まずは進め方を作って、今日の 1 から 3 手に小さくしましょう。",
    replanAi: "AI で更新",
    replanHeuristic: "ルールで更新",
    openReturnHint: "メインクエストがまだ始まっていないのに改善やその他が続くときは、戻し方を開いてください。",
    mirrorTitle: "いまの状況",
    sessionStartTitle: "Session Start",
    sessionStartLead: "始める前に、つながり、成果物、時間、終わり方を決める。",
    activeSessionTitle: "いまの作業",
    activeSessionEmpty: "Session Start から始めて、終わり方を先に決めましょう。",
    todayPlanTitle: "今日の進め方",
    sessionsTitle: "今日のセッション",
    sessionsEmpty: "最初に終えたセッションが、比率や開始遅延の基準になります。",
    blockerTitle: "詰まりの記録",
    blockerLead: "責めずに、詰まっている点だけ書く。",
    fallbackTheme: "いちばん動かしやすい作業から入り、ズレを小さいうちに見つける。",
    fallbackNotes: {
      capacity: "今日の使える時間: {value}",
      noCapacity: "まずは 1 本だけ、時間を切ったセッションを置く。",
      hasSession: "新しく始める前に、いまのセッションを閉じる。",
      needsSessionStart: "Session Start で、始める前のチェックを済ませる。",
    },
    stats: {
      readyQuests: "動かしやすい作業",
      activeSession: "作業中",
      mainToday: "今日のメインクエスト",
      metaToday: "メタ作業",
      switchDensity: "切替回数",
      returnState: "戻し方",
    },
    details: {
      readyQuests: "今日いちばん動かしやすい作業",
      noSession: "まだ作業中のセッションはありません",
      mainToday: "今日のメインクエスト時間",
      metaToday: "回避寄りの改善 / その他",
      switchDensity: "ゴールと種別の切替",
      returnOpen: "戻した方がよさそう",
      returnClear: "このまま進めやすい",
    },
    fields: {
      category: "種別",
      quest: "作業",
      mainConnection: "メインクエストへのつながり",
      timebox: "時間制限",
      artifact: "今回外に出すもの",
      artifactPlaceholder: "メモ、送信済みメッセージ、判断、PR など",
      doneWhen: "終わり条件",
      doneWhenPlaceholder: "どこまで行けば終わりか",
      artifactLeft: "実際に残したもの",
      artifactLeftPlaceholder: "任意ですが、次回の再開が楽になります。",
      blockerTitle: "何が詰まっているか",
      blockerQuest: "関連作業",
      blockerDescription: "説明",
      blockerType: "種類",
      blockerSeverity: "重さ",
    },
    buttons: {
      runGate: "開始前チェック",
      confirmStart: "このセッションを始める",
      openReturnInstead: "先に戻し方を開く",
      finishSession: "セッションを終える",
      recordBlocker: "詰まりを記録する",
    },
    messages: {
      planAi: "AI が今日の進め方を更新しました。",
      planHeuristic: "ルールで今日の進め方を更新しました。",
      gateClear: "開始前チェックが終わりました。始めて大丈夫です。",
      gateRisk: "ズレの気配があります。先に戻し方を開くか、そのまま始めるか選べます。",
      sessionStartedBuild: "セッションを始めました。",
      sessionStartedAvoidant: "セッションを始めました。必要なら、ここから戻し方を開けます。",
      sessionFinished: "セッションを終えました。",
      blockerSaved: "詰まりを記録しました。次の一手が見られます。",
    },
    errors: {
      replan: "今日の進め方を更新できませんでした。",
      startSession: "セッションを始められませんでした。",
      gate: "開始前チェックを通せませんでした。",
      finishSession: "セッションを終えられませんでした。",
      blockerSave: "詰まりを保存できませんでした。",
    },
    labels: {
      doneWhen: "終わり条件",
      timebox: "時間制限",
      artifactLeft: "残したもの",
    },
  },
  portfolio: {
    title: "メインクエストを一つに保ち、並行作業を正直にする",
    lead: "メインクエストを前に置き、同時進行数を守り、保留にはきれいな再開メモを残す。",
    addGoal: "ゴールを追加",
    focusTitle: "いまのメインクエスト",
    focusEmpty: "メインクエストはまだ選ばれていません",
    focusBody: "今週前に置くゴールを一つ選びましょう。",
    settingsTitle: "設定",
    activeTitle: "進行中",
    activeEmpty: "まだ進行中のゴールはありません。",
    backlogTitle: "後ろに置くもの",
    backlogEmpty: "いまは後ろに置くゴールがありません。",
    parkedTitle: "保留中",
    parkedEmpty: "いまは保留中のゴールがありません。",
    resumeQueueTitle: "再開待ち",
    resumeQueueEmpty: "ゴールを保留すると、再開条件がここに出ます。",
    defaults: {
      switchReason: "今週はいちばんこれを前に置きたい。",
      resumeReason: "再開条件がそろった。",
      focusFallback: "今はいちばんこれを前に置きたい。",
      resumeFallback: "再開条件がそろった。",
    },
    stats: {
      focusGoal: "メインクエスト",
      activeGoals: "同時進行数",
      resumeQueue: "再開待ち",
      switches: "切替回数",
      medianResume: "再開まで",
      reviewRate: "ふり返り率",
    },
    details: {
      currentActiveCount: "いまの進行中数",
      resumeQueue: "再開メモ付きの保留ゴール",
      recordedThisWeek: "今週記録された数",
      restartDelay: "保留から再開まで",
      last4Weeks: "直近 4 週",
    },
    fields: {
      activeGoalLimit: "同時進行数",
      switchReason: "なぜいまこれを前に置くのか",
      switchReasonPlaceholder: "なぜこれをメインクエストにするのか",
      resumeReason: "なぜいま再開できるのか",
      resumeReasonPlaceholder: "なぜ今は再開して大丈夫か",
      stopMode: "止め方",
      resumeTrigger: "再開トリガー",
      whyStopNow: "なぜいま止めるか",
      parkingNote: "保留メモ",
      parkingNotePlaceholder: "どこまで進んだかと何が残っているか",
      nextRestartStep: "次に再開する一手",
      triggerDetail: "再開条件の詳細",
      triggerPlaceholder: "いつ戻すか、何がそろえば戻すか",
    },
    buttons: {
      saveLimit: "同時進行数を保存",
      editRoute: "進め方を開く",
      startIntake: "受け取りを始める",
      setFocus: "メインクエストにする",
      activateAndFocus: "動かしてメインクエストにする",
      parkGoal: "保留する",
      resumeGoal: "再開する",
      saveParkingNote: "保留メモを保存",
    },
    queue: {
      missingGoal: "ゴールが見つかりません",
      parkedAgo: "{days} 日前に保留",
      whyStopped: "止めた理由",
      nextRestart: "次にやる最初の一手",
      trigger: "再開条件",
    },
    messages: {
      limitSaved: "同時進行数を更新しました。",
      focusSaved: "メインクエストを更新しました。",
      resumeSaved: "ゴールを再開しました。",
      parkedSaved: "ゴールを保留し、再開メモを残しました。",
    },
    errors: {
      limitSave: "同時進行数を更新できませんでした。",
      focusSave: "メインクエストを切り替えられませんでした。",
      resumeSave: "再開できませんでした。",
      parkSave: "保留にできませんでした。",
    },
  },
  review: {
    title: "メインクエストへの戻りやすさを、比率と遅延で見る",
    lead: "v0.6 では、今までの切替ふり返りに、メインクエスト比率、メタ比率、開始遅延、再開遅延、切替回数、if-then 記入率を足している。",
    noGoalTitle: "ふり返る前に、ゴールを一つ作ってください。",
    addGoal: "ゴールを追加",
    formTitle: "ふり返り入力",
    dailyLeadTitle: "日次指標",
    dailyLeadEmpty: "作業セッションと戻し方が記録されると、ここに指標が出ます。",
    focusCandidatesTitle: "次のメインクエスト候補",
    focusCandidatesLead: "次に前に置くゴールはどれか。",
    savedReviewsTitle: "保存済みのふり返り",
    savedReviewsEmpty: "最初のふり返りが、今後比べる基準になります。",
    stats: {
      mainRatio: "メインクエスト比率",
      metaRatio: "メタ作業比率",
      startDelay: "メインクエスト開始まで",
      resumeDelay: "再開まで",
      switchDensity: "切替回数",
      ifThen: "戻り方ルール記入率",
    },
    details: {
      mainRatio: "メインクエスト時間 / 追跡時間",
      metaRatio: "回避寄りの改善 / その他",
      startDelay: "最初の作業から最初のメインクエストまで",
      resumeDelay: "保留から再開まで",
      switchDensity: "ゴールと種別の切替",
      ifThen: "戻し方で if-then が書かれた割合",
    },
    fields: {
      periodStart: "開始日",
      periodEnd: "終了日",
      summary: "進み具合のまとめ",
      learnings: "切替や再開で得た気づき",
      rerouteNote: "進め方の見直しメモ",
      nextFocus: "次のメインクエスト",
    },
    buttons: {
      saveReview: "ふり返りを保存",
      setFocus: "メインクエストにする",
    },
    messages: {
      saved: "ふり返りを保存しました。",
      focusSaved: "ふり返りからメインクエストを更新しました。",
      focusReason: "ふり返りで次のメインクエストを選んだ。",
    },
    errors: {
      save: "ふり返りを保存できませんでした。",
      focusSave: "メインクエストを更新できませんでした。",
    },
    labels: {
      startDelay: "メインクエスト開始まで",
      resumeDelay: "再開まで",
      switchDensity: "切替回数",
      ifThenCoverage: "戻り方ルール記入率",
      learnings: "気づき",
      reroute: "進め方メモ",
      nextFocus: "次のメインクエスト",
    },
    candidateReason: "今週のメインクエスト候補として整理しやすい。",
  },
  returnFlow: {
    title: "ズレに気づき、一度だけ診断して、次の 15 分を決める",
    lead: "いまの状況、COM-B、WOOP / if-then、判断までを 1 ページで短く進める。",
    noFocusTitle: "まだメインクエストが選ばれていません。",
    noFocusBody: "戻し方を使う前に、ポートフォリオでメインクエストを選んでください。",
    combTitle: "いまの詰まりを決める",
    planTitle: "戻り方を作る",
    decisionTitle: "今回の決め方",
    latestTitle: "直近の戻し方",
    steps: {
      facts: "事実を見る",
      bottleneck: "詰まりを決める",
      plan: "戻り方を作る",
      decision: "今回の決め方",
    },
    stepState: {
      current: "いまここ",
      complete: "完了",
      upcoming: "次",
    },
    stepHelp: {
      facts: "まずは事実だけを見る。",
      bottleneck: "主な詰まりと、最小の勝ちを決める。",
      plan: "WOOP、if-then、次の 15 分を書く。",
      decision: "このまま進むか、変えるか、保留するか、撤退するかを決める。",
    },
    summaryLabels: {
      facts: "いまの状況",
      bottleneck: "最小の勝ち",
      plan: "次の 15 分",
      decision: "判断",
    },
    fields: {
      mainQuest: "メインクエストの作業",
      quest: "関連作業",
      primaryBottleneck: "主な詰まり",
      diagnosisType: "診断種別",
      avoidanceHypothesis: "回避の見立て",
      smallestWin: "最小の勝ち",
      woopPlan: "WOOP",
      woopPlaceholder: "Wish / Outcome / Obstacle / Plan",
      ifThenPlan: "if-then",
      ifThenPlaceholder: "もし X なら、Y する",
      next15mAction: "次の 15 分でやること",
      next15mPlaceholder: "まずはどの一手か",
      decision: "判断",
      reviewDate: "見直し日",
      decisionNote: "補足メモ",
      reason: "理由",
      parkingNote: "保留メモ",
      nextRestartStep: "次に再開する一手",
      resumeTriggerType: "再開条件の種類",
      resumeTriggerText: "再開条件",
    },
    buttons: {
      back: "戻る",
      next: "次へ",
      save: "戻し方を保存",
    },
    messages: {
      saved: "戻し方を保存しました。",
    },
    errors: {
      save: "戻し方を保存できませんでした。",
    },
    labels: {
      next15m: "次の 15 分",
      ifThen: "if-then",
    },
  },
  intake: {
    page: "受け取り",
    titleNew: "ポートフォリオを崩さずに、新しいゴールを受け取る",
    titleEdit: "動かせる形に、ゴールを整える",
    lead: "まずはきれいに受け取り、そのあとで動かせる形に整える。",
    refineAi: "AI で整える",
    refineHeuristic: "ルールで整える",
    saveGoal: "ゴールを保存",
    stats: {
      focus: "メインクエスト",
      active: "同時進行数",
      resume: "再開待ち",
      momentum: "最近の前進",
    },
    details: {
      noFocus: "まだメインクエストはありません",
      active: "いまの進行中数",
      resume: "再開メモ付きの保留ゴール",
      momentum: "直近 7 日で終えた作業数",
    },
    formTitle: "ゴール入力",
    formLeadNew: "新しいゴールを受け取る",
    formLeadEdit: "最低限の入力で大丈夫です",
    draftTitle: "整えた下書き",
    draftLead: "いまの情報から見えていること",
    fields: {
      title: "ゴール名",
      description: "ゴールの説明",
      why: "やる理由",
      deadline: "期限",
      successCriteria: "終わったと言える条件",
      successCriteriaPlaceholder: "1 行に 1 つずつ書く",
      currentState: "いまの状況",
      constraints: "制約",
      constraintsPlaceholder: "1 行に 1 つずつ書く",
      concerns: "気がかり / 止まりそうな点",
      todayCapacity: "今日使える時間",
      todayCapacityPlaceholder: "今日はどれくらいなら現実的に使えそうか",
    },
    draftLabels: {
      mode: "作り方",
      summary: "ゴールの要約",
      success: "終わったと言える条件",
      questions: "まだ残る問い",
      route: "最初の進め方メモ",
    },
    messages: {
      refinedAi: "AI がゴールを整えました。",
      refinedHeuristic: "ルールでゴールを整えました。",
      savedActive: "ゴールを保存しました。次は進め方を作ります。",
      savedBacklog: "ゴールを保存しました。空きができたらポートフォリオから前に出せます。",
      emptyDraft: "整えるボタンを押すと、あいまいなゴールを作業しやすい形にできます。",
    },
    errors: {
      refine: "ゴールを整えられませんでした。",
      save: "ゴールを保存できませんでした。",
    },
  },
  map: {
    page: "進め方",
    noFocusTitle: "まずメインクエストを選んでください。",
    noFocusBody: "進め方は一つのメインクエストにひもづきます。先に前に置くゴールを決めてください。",
    openPortfolio: "ポートフォリオを開く",
    heroTitle: "メインクエストを、再開しやすい段階と作業に分ける",
    lead: "進め方は大きな計画ではなく、再開できる道筋です。節目も作業も小さく保つと、今日の一手が選びやすくなります。",
    generateAi: "AI で下書きを作る",
    generateHeuristic: "ルールで下書きを作る",
    saveRoute: "進め方を保存",
    storedRoute: "保存済みの進め方",
    storedLead: "いまのメインクエストにひもづく進め方です。",
    draftTitle: "編集用の下書き",
    draftLead: "保存する前に、言い回しと大きさを整える。",
    emptyStored: "まだ保存済みの進め方はありません。先に下書きを作ってください。",
    emptyDraft: "下書きを作ると、ここで節目と作業を調整できます。",
    messages: {
      generatedAi: "AI が進め方の下書きを作りました。",
      generatedHeuristic: "ルールで進め方の下書きを作りました。",
      saved: "進め方を保存しました。次は今日の一手を決めます。",
    },
    errors: {
      generate: "進め方の下書きを作れませんでした。",
      save: "進め方を保存できませんでした。",
    },
    fields: {
      routeSummary: "進め方の要約",
      milestoneTitle: "節目の名前",
      targetDate: "目標日",
      description: "説明",
      questTitle: "作業名",
      priority: "優先度",
      type: "種類",
      minutes: "想定時間",
      dueDate: "期限",
    },
    milestoneLabel: "節目",
  },
} as const;

const dictionaries = { ja, en } as const;
export type CopyDictionary = typeof en;

const labelMaps: Record<UiLocale, Record<string, string>> = {
  ja: {
    active: "進行中",
    planned: "予定",
    ready: "準備完了",
    suggested: "提案",
    in_progress: "進行中",
    completed: "完了",
    blocked: "詰まり",
    overdue: "期限超過",
    open: "未解決",
    resolved: "解消",
    high: "高",
    medium: "中",
    low: "低",
    draft: "下書き",
    paused: "一時停止",
    abandoned: "中止",
    hold: "保留",
    shrink: "縮小",
    cancel: "取りやめ",
    waiting: "再開待ち",
    resumed: "再開済み",
    manual: "手動",
    date: "日付",
    condition: "条件",
    heuristic: "ルール",
    ai: "AI",
    supabase: "Supabase",
    "local-file": "ローカル",
    "browser-local": "ブラウザ保存",
    main: "メイン",
    improve: "改善",
    admin: "事務",
    other: "その他",
    side: "サブ",
    direct: "直接",
    supporting: "支援",
    unclear: "不明",
    build: "メイン投資",
    avoidant: "回避寄り",
    fight: "このまま進む",
    detour: "少し変えて進む",
    retreat: "撤退",
    capability: "やり方",
    opportunity: "環境",
    motivation: "気力",
    clarity: "不明瞭",
    time: "時間",
    decision: "判断",
    dependency: "依存",
    energy: "エネルギー",
    unknown: "その他",
  },
  en: {
    active: "Active",
    planned: "Planned",
    ready: "Ready",
    suggested: "Suggested",
    in_progress: "In progress",
    completed: "Completed",
    blocked: "Blocked",
    overdue: "Overdue",
    open: "Open",
    resolved: "Resolved",
    high: "High",
    medium: "Medium",
    low: "Low",
    draft: "Draft",
    paused: "Paused",
    abandoned: "Abandoned",
    hold: "Hold",
    shrink: "Shrink",
    cancel: "Cancel",
    waiting: "Waiting",
    resumed: "Resumed",
    manual: "Manual",
    date: "Date",
    condition: "Condition",
    heuristic: "Heuristic",
    ai: "AI",
    supabase: "Supabase",
    "local-file": "Local file",
    "browser-local": "Browser local",
    main: "Main",
    improve: "Improve",
    admin: "Admin",
    other: "Other",
    side: "Side",
    direct: "Direct",
    supporting: "Supporting",
    unclear: "Unclear",
    build: "Build",
    avoidant: "Avoidant",
    fight: "Fight",
    detour: "Detour",
    retreat: "Retreat",
    capability: "Capability",
    opportunity: "Opportunity",
    motivation: "Motivation",
    clarity: "Clarity",
    time: "Time",
    decision: "Decision",
    dependency: "Dependency",
    energy: "Energy",
    unknown: "Unknown",
  },
};

export function getCopy(locale: UiLocale): CopyDictionary {
  return (dictionaries[locale] ?? dictionaries.ja) as CopyDictionary;
}

export function getLabel(locale: UiLocale, value: string): string {
  return labelMaps[locale]?.[value] ?? value.replace(/_/g, " ");
}

export function localizeRuntimeError(_locale: UiLocale, error: unknown, fallback: string): string {
  if (error instanceof Error && error.message.trim()) {
    return error.message;
  }
  if (typeof error === "string" && error.trim()) {
    return error;
  }
  return fallback;
}

export function interpolate(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, key) => String(values[key] ?? `{${key}}`));
}





