import type { UiLocale } from "@/lib/quest-agent/types";

const en = {
  nav: {
    portfolio: "Portfolio",
    intake: "Intake",
    map: "Map",
    today: "Today",
    returnFlow: "Return",
    review: "Review",
  },
  shell: {
    kicker: "Quest Agent v0.6",
    title: "Keep moving, and make returning cheaper when you stall.",
    description: "One focus goal, a clear today plan, and a gentle return loop when momentum drops.",
    mirror: "Current state",
    focus: "Focus",
    nextRestart: "Next restart",
    portfolioHealth: "Portfolio health",
    healthTitle: "Choose the work, notice drift, then return in 15 minutes.",
    activeGoals: "Active goals",
    mainToday: "Main today",
    switchDensity: "Switches",
    activeGoalsPill: "Active",
    localeLabel: "Language",
    languageJa: "Japanese",
    languageEn: "English",
  },
  common: {
    openPortfolio: "Open Portfolio",
    openToday: "Open Today",
    openReturn: "Open Return",
    openMap: "Open Map",
    backToToday: "Back to Today",
    cancel: "Cancel",
    save: "Save",
    running: "Running",
    noSummary: "No summary yet.",
    noData: "No data yet.",
    minutes: "m",
  },
  today: {
    title: "Turn the route into a clean work block for today.",
    lead: "Check the route, start a session, and use Return when drift shows up.",
    noFocusTitle: "No focus goal is selected.",
    noFocusBody: "Choose the goal you want to protect first.",
    noRouteTitle: "This focus goal needs a route first.",
    noRouteBody: "Create the route first so today can shrink into 1 to 3 concrete steps.",
    replanAi: "Refresh today with AI",
    replanHeuristic: "Refresh today",
    openReturnHint: "Something looks off. Open Return to make the next move easier.",
    mirrorTitle: "Mirror",
    sessionStartTitle: "Session start",
    sessionStartLead: "Define the artifact, the finish line, and the timebox before you start.",
    activeSessionTitle: "Active session",
    activeSessionEmpty: "No active session. Start one when you are ready.",
    todayPlanTitle: "Today's route",
    sessionsTitle: "Today's sessions",
    sessionsEmpty: "No finished sessions yet.",
    blockerTitle: "Blockers",
    blockerLead: "Record the blocker so Quest Agent can suggest a reroute.",
    stats: {
      readyQuests: "Ready quests",
      activeSession: "Active session",
      mainToday: "Main today",
      metaToday: "Meta work",
      switchDensity: "Switch density",
      returnState: "Return",
    },
    details: {
      readyQuests: "Quests that are ready to move today",
      noSession: "No session is running",
      mainToday: "Minutes spent on direct progress today",
      metaToday: "Minutes spent on setup, drift, or admin today",
      switchDensity: "Goal and category changes recorded today",
      returnOpen: "Open",
      returnClear: "Clear",
    },
    fields: {
      category: "Category",
      quest: "Quest",
      mainConnection: "Main connection",
      timebox: "Timebox",
      artifact: "Artifact commitment",
      artifactPlaceholder: "What concrete output should exist when this session ends?",
      doneWhen: "Done when",
      doneWhenPlaceholder: "What tells you this session is complete?",
      artifactLeft: "Artifact note",
      artifactLeftPlaceholder: "What should future-you know when resuming this?",
      blockerTitle: "Blocker title",
      blockerQuest: "Related quest",
      blockerDescription: "Blocker description",
      blockerType: "Blocker type",
      blockerSeverity: "Severity",
    },
    buttons: {
      runGate: "Run gate check",
      confirmStart: "Start session",
      openReturnInstead: "Open Return instead",
      finishSession: "Finish session",
      recordBlocker: "Record blocker",
    },
    messages: {
      planAi: "AI refreshed today's route.",
      planHeuristic: "Heuristic mode refreshed today's route.",
      gateRisk: "This looks like drift. Return is a better next step.",
      gateClear: "Gate check passed. You can start now.",
      sessionStartedBuild: "Session started.",
      sessionStartedAvoidant: "Session started, but this looked avoidant. Keep Return nearby.",
      sessionFinished: "Session finished.",
      blockerSaved: "Blocker recorded. The reroute hint is ready.",
    },
    labels: {
      doneWhen: "Done when",
      timebox: "Timebox",
      artifactLeft: "Artifact note",
    },
  },
  portfolio: {
    title: "Keep one clear front slot and a clean resume queue.",
    lead: "Portfolio decides what stays active, what waits, and what should return later.",
    addGoal: "Add a goal",
    focusTitle: "Focus goal",
    focusBody: "This is the goal that gets the front slot right now.",
    focusEmpty: "No focus goal selected.",
    activeTitle: "Active goals",
    activeEmpty: "No active goals yet.",
    backlogTitle: "Backlog",
    backlogEmpty: "No backlog goals.",
    parkedTitle: "Parked goals",
    parkedEmpty: "No parked goals.",
    resumeQueueTitle: "Resume queue",
    resumeQueueEmpty: "Nothing is waiting to resume.",
    stats: {
      focusGoal: "Focus goal",
      activeGoals: "Active goals",
      resumeQueue: "Resume queue",
      switches: "Switches",
      medianResume: "Median restart delay",
      reviewRate: "Review rate",
    },
    details: {
      currentActiveCount: "Current active count",
      resumeQueue: "Goals parked with restart notes",
      recordedThisWeek: "Switches recorded this week",
      restartDelay: "Median time before a parked goal resumed",
      last4Weeks: "Completion rate in the last 4 weeks",
    },
    fields: {
      activeGoalLimit: "Active goal limit",
      switchReason: "Why should this become the focus now?",
      switchReasonPlaceholder: "Why this goal, now?",
      resumeReason: "Why is it safe to resume now?",
      resumeReasonPlaceholder: "What changed so this can move again?",
      stopMode: "Stop mode",
      resumeTrigger: "Resume trigger type",
      whyStopNow: "Why stop now?",
      parkingNote: "Parking note",
      parkingNotePlaceholder: "Leave a note that reduces restart cost.",
      nextRestartStep: "Next restart step",
      triggerDetail: "Resume trigger detail",
      triggerPlaceholder: "What date or condition should reopen this goal?",
    },
    buttons: {
      saveLimit: "Save limit",
      setFocus: "Set focus",
      activateAndFocus: "Activate and focus",
      parkGoal: "Park goal",
      resumeGoal: "Resume goal",
      startIntake: "Open intake",
      saveParkingNote: "Save park note",
      editRoute: "Open route",
    },
    messages: {
      limitSaved: "Active goal limit updated.",
      focusSaved: "Focus goal updated.",
      resumeSaved: "Goal resumed.",
      parkedSaved: "Goal parked with a restart note.",
    },
    queue: {
      whyStopped: "Why it stopped",
      nextRestart: "Next restart",
      trigger: "Trigger",
      parkedAgo: "Parked {days}d ago",
      missingGoal: "This goal is no longer available.",
    },
  },
  review: {
    title: "Review what moved, what drifted, and what should be the next focus.",
    lead: "Weekly review saves the learning and sharpens the next route.",
    noGoalTitle: "Add a goal first.",
    addGoal: "Open intake",
    formTitle: "Weekly review",
    dailyLeadTitle: "Daily lead metrics",
    dailyLeadEmpty: "No daily metrics yet.",
    focusCandidatesTitle: "Focus candidates",
    focusCandidatesLead: "Pick the clearest next front-slot candidate.",
    savedReviewsTitle: "Saved reviews",
    savedReviewsEmpty: "No weekly reviews saved yet.",
    stats: {
      mainRatio: "Main ratio",
      metaRatio: "Meta ratio",
      startDelay: "Start delay",
      resumeDelay: "Resume delay",
      switchDensity: "Switch density",
      ifThen: "If-then coverage",
    },
    details: {
      mainRatio: "Main session time / tracked time",
      metaRatio: "Avoidant improve / other",
      startDelay: "First session to first main",
      resumeDelay: "Parked to resumed",
      switchDensity: "Goal + category changes",
      ifThen: "Return runs with if-then",
    },
    fields: {
      periodStart: "Period start",
      periodEnd: "Period end",
      summary: "Progress summary",
      learnings: "Switching / resumption learnings",
      rerouteNote: "Reroute note",
      nextFocus: "Next focus",
    },
    buttons: {
      saveReview: "Save weekly review",
      setFocus: "Set focus",
    },
    messages: {
      saved: "Review saved.",
      focusSaved: "Focus goal updated from review.",
    },
    labels: {
      startDelay: "Start delay",
      resumeDelay: "Resume delay",
      switchDensity: "Switch density",
      ifThenCoverage: "If-then coverage",
      learnings: "Learnings",
      reroute: "Reroute",
      nextFocus: "Next focus",
    },
    candidateReason: "This looks like the clearest next front-slot candidate.",
  },
  returnFlow: {
    title: "See the facts, choose the bottleneck, then return in the next 15 minutes.",
    lead: "Return stays on one screen: see the facts, choose the bottleneck, make a return plan, then choose the decision.",
    noFocusTitle: "No focus goal is selected.",
    noFocusBody: "Choose a focus goal first so Return knows what it is trying to protect.",
    combTitle: "COM-B interview",
    planTitle: "WOOP / if-then",
    decisionTitle: "Decision",
    latestTitle: "Latest return",
    steps: {
      facts: "See the facts",
      bottleneck: "Choose the bottleneck",
      plan: "Make the return plan",
      decision: "Choose the decision",
    },
    stepState: {
      current: "Current",
      complete: "Done",
      upcoming: "Next",
    },
    stepHelp: {
      facts: "Start with Mirror and today's metrics so the situation is clear without blame.",
      bottleneck: "Choose the one main quest and the main bottleneck to work on.",
      plan: "Use WOOP and if-then to make the next 15 minutes easy to start.",
      decision: "Choose whether to fight, detour, hold, or retreat.",
    },
    summaryLabels: {
      facts: "Visible facts",
      bottleneck: "Current diagnosis",
      plan: "Next 15 minutes",
      decision: "Decision",
    },
    fields: {
      mainQuest: "Main quest",
      quest: "Quest",
      primaryBottleneck: "Primary bottleneck",
      diagnosisType: "Diagnosis to act on",
      avoidanceHypothesis: "Avoidance hypothesis",
      smallestWin: "Smallest win",
      woopPlan: "WOOP plan",
      woopPlaceholder: "Wish / Outcome / Obstacle / Plan",
      ifThenPlan: "If-then",
      ifThenPlaceholder: "If X happens, then I will Y.",
      next15mAction: "Next 15 minutes",
      next15mPlaceholder: "What exactly should happen in the next 15 minutes?",
      decision: "Decision",
      reviewDate: "Review date",
      decisionNote: "Decision note",
      reason: "Reason",
      parkingNote: "Parking note",
      nextRestartStep: "Next restart step",
      resumeTriggerType: "Resume trigger type",
      resumeTriggerText: "Resume trigger",
    },
    buttons: {
      back: "Back",
      next: "Next",
      save: "Save return flow",
    },
    messages: {
      saved: "Return flow saved.",
    },
    labels: {
      next15m: "Next 15 minutes",
      ifThen: "If-then",
    },
  },
} as const;

const ja = {
  ...en,
  nav: {
    portfolio: "ポートフォリオ",
    intake: "受け取り",
    map: "マップ",
    today: "Today",
    returnFlow: "Return",
    review: "レビュー",
  },
  shell: {
    ...en.shell,
    title: "前に進みながら、止まったら戻りやすくする。",
    description: "本丸を1つ決めて、Today で進め、止まったら Return で立て直します。",
    mirror: "現在地",
    focus: "本丸",
    nextRestart: "次の再開",
    portfolioHealth: "ポートフォリオ健全性",
    healthTitle: "進める仕事を選び、ズレに気づき、15分で戻る。",
    activeGoals: "進行中",
    mainToday: "本丸時間",
    switchDensity: "切替密度",
    activeGoalsPill: "進行中",
    localeLabel: "表示言語",
    languageJa: "日本語",
    languageEn: "English",
  },
  common: {
    ...en.common,
    openPortfolio: "ポートフォリオを開く",
    openToday: "Today を開く",
    openReturn: "Return を開く",
    openMap: "Map を開く",
    backToToday: "Today に戻る",
    cancel: "キャンセル",
    save: "保存",
    running: "進行中",
    noSummary: "まだ概要がありません。",
    noData: "まだデータがありません。",
    minutes: "分",
  },
  today: {
    ...en.today,
    title: "今日の進め方を、無理のない1ブロックにする。",
    lead: "ルートを見直し、作業を始め、ズレたら Return で立て直します。",
    noFocusTitle: "まだ本丸が決まっていません。",
    noFocusBody: "まずは守りたい目標を1つ選びます。",
    noRouteTitle: "この本丸にはまだルートがありません。",
    noRouteBody: "先に Quest Map を作ると、今日の一手まで小さくできます。",
    replanAi: "AI で今日を更新",
    replanHeuristic: "今日を更新",
    openReturnHint: "いまは Return を開くほうが前に進みやすそうです。",
    mirrorTitle: "Mirror",
    sessionStartTitle: "セッション開始",
    sessionStartLead: "何を残すか、どこで終えるか、何分使うかを先に決めます。",
    activeSessionTitle: "進行中のセッション",
    activeSessionEmpty: "進行中のセッションはありません。",
    todayPlanTitle: "今日のルート",
    sessionsTitle: "今日のセッション",
    sessionsEmpty: "まだ終えたセッションはありません。",
    blockerTitle: "詰まり",
    blockerLead: "詰まりを残しておくと、迂回案を出しやすくなります。",
    stats: {
      readyQuests: "着手可能",
      activeSession: "進行中セッション",
      mainToday: "本丸時間",
      metaToday: "メタ作業",
      switchDensity: "切替密度",
      returnState: "Return",
    },
    details: {
      readyQuests: "今日着手しやすい Quest の数",
      noSession: "進行中のセッションはありません",
      mainToday: "本丸に向いた時間",
      metaToday: "準備や管理に使った時間",
      switchDensity: "今日の切替回数",
      returnOpen: "要確認",
      returnClear: "安定",
    },
    buttons: {
      runGate: "開始前チェック",
      confirmStart: "始める",
      openReturnInstead: "Return を開く",
      finishSession: "終える",
      recordBlocker: "詰まりを記録",
    },
    messages: {
      planAi: "AI が今日のルートを更新しました。",
      planHeuristic: "今日のルートを更新しました。",
      gateRisk: "いまは Return を挟むほうが良さそうです。",
      gateClear: "そのまま始めて大丈夫です。",
      sessionStartedBuild: "セッションを開始しました。",
      sessionStartedAvoidant: "開始しましたが、少しズレ気味です。Return を近くに置いておきます。",
      sessionFinished: "セッションを終了しました。",
      blockerSaved: "詰まりを記録しました。",
    },
    labels: {
      doneWhen: "終わり条件",
      timebox: "時間枠",
      artifactLeft: "残しメモ",
    },
  },
  portfolio: {
    ...en.portfolio,
    title: "本丸を1つに絞り、再開しやすい待機列を保つ。",
    lead: "Portfolio は、いま動かすもの、待たせるもの、あとで戻すものを整理します。",
    addGoal: "ゴールを追加",
    focusTitle: "本丸",
    focusBody: "いま前に置くゴールです。",
    focusEmpty: "まだ本丸はありません。",
    activeTitle: "進行中のゴール",
    activeEmpty: "進行中のゴールはありません。",
    backlogTitle: "バックログ",
    backlogEmpty: "バックログは空です。",
    parkedTitle: "保留中のゴール",
    parkedEmpty: "保留中のゴールはありません。",
    resumeQueueTitle: "再開待ち",
    resumeQueueEmpty: "再開待ちはありません。",
    stats: {
      focusGoal: "本丸",
      activeGoals: "進行中",
      resumeQueue: "再開待ち",
      switches: "切替回数",
      medianResume: "再開までの中央値",
      reviewRate: "レビュー率",
    },
    details: {
      currentActiveCount: "現在の同時進行数",
      resumeQueue: "再開メモ付きで止めたもの",
      recordedThisWeek: "今週記録した切替",
      restartDelay: "止めてから再開までの時間",
      last4Weeks: "直近4週間の完了率",
    },
    buttons: {
      saveLimit: "上限を保存",
      setFocus: "本丸にする",
      activateAndFocus: "有効化して本丸にする",
      parkGoal: "保留にする",
      resumeGoal: "再開する",
      startIntake: "受け取りを開く",
      saveParkingNote: "保留メモを保存",
      editRoute: "ルートを開く",
    },
    messages: {
      limitSaved: "同時進行数を更新しました。",
      focusSaved: "本丸を更新しました。",
      resumeSaved: "再開しました。",
      parkedSaved: "再開メモ付きで保留しました。",
    },
    queue: {
      whyStopped: "止めた理由",
      nextRestart: "次の再開",
      trigger: "再開条件",
      parkedAgo: "{days}日前に保留",
      missingGoal: "このゴールは見つかりません。",
    },
  },
  review: {
    ...en.review,
    title: "進んだこと、ズレたこと、次に前へ置くものを見直す。",
    lead: "週次レビューで学びを残し、次のルートをはっきりさせます。",
    noGoalTitle: "先にゴールを追加しましょう。",
    addGoal: "受け取りを開く",
    formTitle: "週次レビュー",
    dailyLeadTitle: "日次メトリクス",
    dailyLeadEmpty: "まだ日次メトリクスはありません。",
    focusCandidatesTitle: "次の本丸候補",
    focusCandidatesLead: "次に前へ置く候補を見比べます。",
    savedReviewsTitle: "保存済みレビュー",
    savedReviewsEmpty: "まだレビューはありません。",
    stats: {
      mainRatio: "本丸比率",
      metaRatio: "メタ比率",
      startDelay: "開始遅延",
      resumeDelay: "再開遅延",
      switchDensity: "切替密度",
      ifThen: "if-then 率",
    },
    labels: {
      startDelay: "開始遅延",
      resumeDelay: "再開遅延",
      switchDensity: "切替密度",
      ifThenCoverage: "if-then 率",
      learnings: "学び",
      reroute: "迂回",
      nextFocus: "次の本丸",
    },
    messages: {
      saved: "レビューを保存しました。",
      focusSaved: "レビューから本丸を更新しました。",
    },
    candidateReason: "次に前へ置く候補として分かりやすいです。",
  },
  returnFlow: {
    ...en.returnFlow,
    title: "事実を見て、詰まりを決めて、次の15分に戻す。",
    lead: "Return は1画面で終えます。事実を見る、詰まりを決める、戻り方を作る、最後に決める、の順です。",
    noFocusTitle: "まだ本丸が決まっていません。",
    noFocusBody: "何に戻すかをはっきりさせるため、先に本丸を選びます。",
    combTitle: "COM-B で詰まりを見る",
    planTitle: "WOOP / if-then",
    decisionTitle: "戻り方を決める",
    latestTitle: "直近の Return",
    steps: {
      facts: "事実を見る",
      bottleneck: "詰まりを決める",
      plan: "戻り方を作る",
      decision: "方針を決める",
    },
    stepState: {
      current: "現在",
      complete: "完了",
      upcoming: "次",
    },
    stepHelp: {
      facts: "Mirror と今日の数字を見て、責めずに現状を把握します。",
      bottleneck: "いま戻りたい Main Quest と、いちばん大きい詰まりを1つに絞ります。",
      plan: "WOOP と if-then で、次の15分を始めやすくします。",
      decision: "続行、迂回、保留、撤退のどれで戻るかを決めます。",
    },
    summaryLabels: {
      facts: "見えている事実",
      bottleneck: "いまの診断",
      plan: "次の15分",
      decision: "決定",
    },
    buttons: {
      back: "戻る",
      next: "次へ",
      save: "戻り方を保存",
    },
    messages: {
      saved: "戻り方を保存しました。",
    },
    labels: {
      next15m: "次の15分",
      ifThen: "if-then",
    },
  },
} as const;

const copy: Record<UiLocale, typeof en> = { ja, en };

const labelMap: Record<UiLocale, Record<string, string>> = {
  ja: {
    draft: "下書き",
    active: "進行中",
    paused: "停止中",
    completed: "完了",
    abandoned: "中止",
    planned: "予定",
    ready: "準備完了",
    in_progress: "進行中",
    blocked: "詰まり中",
    open: "未解決",
    resolved: "解決済み",
    high: "高",
    medium: "中",
    low: "低",
    hold: "保留",
    shrink: "縮小",
    cancel: "中止",
    waiting: "待機中",
    resumed: "再開済み",
    manual: "手動",
    date: "日付",
    condition: "条件",
    heuristic: "ルール",
    ai: "AI",
    supabase: "Supabase",
    "local-file": "ローカルファイル",
    "browser-local": "ブラウザ保存",
    main: "メイン",
    side: "サイド",
    improve: "改善",
    admin: "管理",
    other: "その他",
    direct: "直進",
    supporting: "支援",
    unclear: "不明",
    build: "作る",
    avoidant: "回避的",
    fight: "続行",
    detour: "迂回",
    retreat: "撤退",
    capability: "能力",
    opportunity: "機会",
    motivation: "動機",
    clarity: "明確さ",
    time: "時間",
    decision: "判断",
    dependency: "依存",
    energy: "エネルギー",
    unknown: "不明",
    suggested: "提案",
  },
  en: {
    draft: "Draft",
    active: "Active",
    paused: "Paused",
    completed: "Completed",
    abandoned: "Abandoned",
    planned: "Planned",
    ready: "Ready",
    in_progress: "In progress",
    blocked: "Blocked",
    open: "Open",
    resolved: "Resolved",
    high: "High",
    medium: "Medium",
    low: "Low",
    hold: "Hold",
    shrink: "Shrink",
    cancel: "Cancel",
    waiting: "Waiting",
    resumed: "Resumed",
    manual: "Manual",
    date: "Date",
    condition: "Condition",
    heuristic: "Heuristic",
    ai: "AI",
    supabase: "Supabase",
    "local-file": "Local file",
    "browser-local": "Browser local",
    main: "Main",
    side: "Side",
    improve: "Improve",
    admin: "Admin",
    other: "Other",
    direct: "Direct",
    supporting: "Supporting",
    unclear: "Unclear",
    build: "Build",
    avoidant: "Avoidant",
    fight: "Fight",
    detour: "Detour",
    retreat: "Retreat",
    capability: "Capability",
    opportunity: "Opportunity",
    motivation: "Motivation",
    clarity: "Clarity",
    time: "Time",
    decision: "Decision",
    dependency: "Dependency",
    energy: "Energy",
    unknown: "Unknown",
    suggested: "Suggested",
  },
};

const runtimeErrors: Record<UiLocale, Record<string, string>> = {
  ja: {
    "Request failed.": "通信に失敗しました。もう一度お試しください。",
    "Goal not found.": "ゴールが見つかりません。",
    "Build vs Improve decision not found.": "開始前チェックが見つかりません。",
    "Work session not found.": "作業セッションが見つかりません。",
    "The active goal limit is full. Park or complete another goal before activating this one.": "同時進行の上限に達しています。先に別のゴールを保留または完了してください。",
    "Park or complete an active goal before lowering the active limit.": "上限を下げる前に、進行中のゴールを整理してください。",
    "Completed goals cannot become the focus goal.": "完了したゴールは本丸にできません。",
    "This goal is parked. Resume it from the queue so the restart note stays attached.": "このゴールは保留中です。再開待ちから戻してください。",
    "Completed goals do not need to be parked.": "完了したゴールは保留にする必要がありません。",
    "This goal is not waiting in the resume queue.": "このゴールは再開待ちにありません。",
    "Invalid UI preferences payload.": "表示設定の内容が正しくありません。",
    "Failed to update UI preferences.": "表示設定を更新できませんでした。",
  },
  en: {},
};

function humanize(value: string) {
  return value.replaceAll("_", " ");
}

export function getCopy(locale: UiLocale) {
  return copy[locale] ?? en;
}

export function getLabel(locale: UiLocale, value: string) {
  return labelMap[locale]?.[value] ?? labelMap.en[value] ?? humanize(value);
}

export function localizeRuntimeError(locale: UiLocale, error: unknown, fallback: string) {
  if (error instanceof Error) {
    return runtimeErrors[locale]?.[error.message] ?? fallback;
  }
  return fallback;
}

export function interpolate(template: string, values: Record<string, string | number>) {
  return Object.entries(values).reduce((result, [key, value]) => result.replaceAll(`{${key}}`, String(value)), template);
}

