import type { UiLocale } from "@/lib/quest-agent/types";

const en = {
  nav: {
    portfolio: "Portfolio",
    intake: "Intake",
    map: "Map",
    today: "Today",
    returnFlow: "Return",
    review: "Review",
  },
  shell: {
    kicker: "Quest Agent v0.6",
    title: "Keep moving, and make returning cheaper when you stall.",
    description: "One focus goal, a clear today plan, and a gentle return loop when momentum drops.",
    mirror: "Current state",
    focus: "Focus",
    nextRestart: "Next restart",
    portfolioHealth: "Portfolio health",
    healthTitle: "Choose the work, notice drift, then return in 15 minutes.",
    activeGoals: "Active goals",
    mainToday: "Main today",
    switchDensity: "Switches",
    activeGoalsPill: "Active",
    localeLabel: "Language",
    languageJa: "Japanese",
    languageEn: "English",
  },
  common: {
    openPortfolio: "Open Portfolio",
    openToday: "Open Today",
    openReturn: "Open Return",
    openMap: "Open Map",
    cancel: "Cancel",
    minutes: "min",
    running: "running",
    noSummary: "No summary yet.",
    noData: "No data yet.",
    backToToday: "Back to Today",
  },
  today: {
    title: "Set up today lightly, then return quickly if work drifts.",
    lead: "Session Start stays light, Mirror stays factual, and Return opens only when it helps.",
    noFocusTitle: "No focus goal is selected.",
    noFocusBody: "Choose one focus goal in Portfolio before shrinking today into a small block.",
    noRouteTitle: "This focus goal needs a route first.",
    noRouteBody: "Create the route first so today can shrink into 1 to 3 concrete steps.",
    replanAi: "Replan with AI",
    replanHeuristic: "Replan heuristically",
    openReturnHint: "Use Return when improve or other work keeps stacking up before main work starts.",
    mirrorTitle: "Mirror",
    sessionStartTitle: "Session Start",
    sessionStartLead: "Decide the connection, artifact, timebox, and end condition before you begin.",
    activeSessionTitle: "Active session",
    activeSessionEmpty: "Use Session Start to choose the category and end condition before you begin.",
    todayPlanTitle: "Today plan",
    sessionsTitle: "Today sessions",
    sessionsEmpty: "The first finished block becomes the baseline for main ratio and start delay.",
    blockerTitle: "Blocker intake",
    blockerLead: "Name the stall without blame.",
    stats: {
      readyQuests: "Ready quests",
      activeSession: "Active session",
      mainToday: "Main today",
      metaToday: "Meta today",
      switchDensity: "Switch density",
      returnState: "Return",
    },
    details: {
      readyQuests: "The easiest quests to move today",
      noSession: "No session running",
      mainToday: "Main session time today",
      metaToday: "Avoidant improve / other",
      switchDensity: "Goal + category changes",
      returnOpen: "Open",
      returnClear: "Clear",
    },
    fields: {
      category: "Category",
      quest: "Quest",
      mainConnection: "Connection to main work",
      timebox: "Time limit",
      artifact: "What will leave this session?",
      artifactPlaceholder: "A note, sent message, decision, PR, or other visible output",
      doneWhen: "Stop when",
      doneWhenPlaceholder: "What makes this block done?",
      artifactLeft: "Artifact actually left",
      artifactLeftPlaceholder: "Optional, but it helps the next restart.",
      blockerTitle: "What is stuck?",
      blockerQuest: "Related quest",
      blockerDescription: "Description",
      blockerType: "Type",
      blockerSeverity: "Severity",
    },
    buttons: {
      runGate: "Run gate",
      confirmStart: "Start this session",
      openReturnInstead: "Open Return instead",
      finishSession: "Finish session",
      recordBlocker: "Record blocker",
    },
    messages: {
      planAi: "AI refreshed today's route.",
      planHeuristic: "Heuristic mode refreshed today's route.",
      gateClear: "Gate checked. You can begin now.",
      gateRisk: "The gate sees some drift risk. You can open Return first or confirm anyway.",
      sessionStartedBuild: "Session started.",
      sessionStartedAvoidant: "Session started. You can still open Return if needed.",
      sessionFinished: "Work session finished.",
      blockerSaved: "Blocker recorded. The reroute hint is ready.",
    },
    labels: {
      doneWhen: "Done when",
      timebox: "Timebox",
      artifactLeft: "Artifact left",
    },
  },
  portfolio: {
    title: "Keep one front goal clear and keep parallel work honest.",
    lead: "One focus goal stays in front, the active limit stays real, and parked work keeps a clean restart note.",
    addGoal: "Add goal",
    focusTitle: "Current focus",
    focusEmpty: "No focus goal selected",
    focusBody: "Choose one goal to stay front-and-center this week.",
    activeTitle: "Active",
    activeEmpty: "No active goals yet.",
    backlogTitle: "Backlog",
    backlogEmpty: "No backlog goals right now.",
    parkedTitle: "Parked",
    parkedEmpty: "No parked goals right now.",
    resumeQueueTitle: "Resume queue",
    resumeQueueEmpty: "When you park a goal, its restart conditions appear here.",
    stats: {
      focusGoal: "Focus goal",
      activeGoals: "Active goals",
      resumeQueue: "Resume queue",
      switches: "Switches",
      medianResume: "Median resume",
      reviewRate: "Review rate",
    },
    details: {
      currentActiveCount: "Current active count",
      resumeQueue: "Goals parked with restart notes",
      recordedThisWeek: "Recorded this week",
      restartDelay: "Delay until restart",
      last4Weeks: "Last 4 weeks",
    },
    fields: {
      activeGoalLimit: "Active goal limit",
      switchReason: "Why move this to the front now?",
      switchReasonPlaceholder: "Why should this become the focus now?",
      resumeReason: "Why is this ready to restart?",
      resumeReasonPlaceholder: "Why can this restart now?",
      stopMode: "Stop mode",
      resumeTrigger: "Resume trigger",
      whyStopNow: "Why stop now?",
      parkingNote: "Parking note",
      parkingNotePlaceholder: "Where did you stop and what remains?",
      nextRestartStep: "Next restart step",
      triggerDetail: "Trigger detail",
      triggerPlaceholder: "When should this come back?",
    },
    buttons: {
      saveLimit: "Save limit",
      editRoute: "Open route",
      startIntake: "Start intake",
      setFocus: "Set focus",
      activateAndFocus: "Activate + Focus",
      parkGoal: "Park goal",
      resumeGoal: "Resume goal",
      saveParkingNote: "Save parking note",
    },
    queue: {
      missingGoal: "Missing goal",
      parkedAgo: "Parked {days} day(s) ago",
      whyStopped: "Why stopped",
      nextRestart: "Next restart step",
      trigger: "Trigger",
    },
    messages: {
      limitSaved: "Active goal limit updated.",
      focusSaved: "Focus goal updated.",
      resumeSaved: "Goal resumed and moved back toward focus.",
      parkedSaved: "Goal moved into the resume queue with a restart note.",
    },
  },
  review: {
    title: "Review how easy it is to come back by looking at ratios and delays.",
    lead: "v0.6 keeps the switching review and adds main ratio, meta ratio, start delay, resume delay, switch density, and if-then coverage.",
    noGoalTitle: "You need at least one goal before you can review the portfolio.",
    addGoal: "Add goal",
    formTitle: "Review form",
    dailyLeadTitle: "Daily lead metrics",
    dailyLeadEmpty: "Daily metrics appear after work sessions and return runs are recorded.",
    focusCandidatesTitle: "Next focus candidates",
    focusCandidatesLead: "Which goal should get the front slot next?",
    savedReviewsTitle: "Saved reviews",
    savedReviewsEmpty: "The first review becomes the baseline for future comparisons.",
    stats: {
      mainRatio: "Main ratio",
      metaRatio: "Meta ratio",
      startDelay: "Start delay",
      resumeDelay: "Resume delay",
      switchDensity: "Switch density",
      ifThen: "If-then coverage",
    },
    details: {
      mainRatio: "Main session time / tracked time",
      metaRatio: "Avoidant improve / other",
      startDelay: "First session to first main",
      resumeDelay: "Parked to resumed",
      switchDensity: "Goal + category changes",
      ifThen: "Return runs with if-then",
    },
    fields: {
      periodStart: "Period start",
      periodEnd: "Period end",
      summary: "Progress summary",
      learnings: "Switching / resumption learnings",
      rerouteNote: "Reroute note",
      nextFocus: "Next focus",
    },
    buttons: {
      saveReview: "Save weekly review",
      setFocus: "Set focus",
    },
    messages: {
      saved: "Review saved.",
      focusSaved: "Focus goal updated from review.",
    },
    labels: {
      startDelay: "Start delay",
      resumeDelay: "Resume delay",
      switchDensity: "Switch density",
      ifThenCoverage: "If-then coverage",
      learnings: "Learnings",
      reroute: "Reroute",
      nextFocus: "Next focus",
    },
    candidateReason: "This looks easy to organize as a front-slot candidate this week.",
  },
  returnFlow: {
    title: "Notice the drift, diagnose it once, then choose the next 15 minutes.",
    lead: "Move through Mirror, COM-B, WOOP / if-then, and the decision in one calm page.",
    noFocusTitle: "No focus goal is selected.",
    noFocusBody: "Pick a focus goal in Portfolio before using Return.",
    combTitle: "Name the main bottleneck",
    planTitle: "Build the return plan",
    decisionTitle: "Choose what this means",
    latestTitle: "Latest return",
    steps: {
      facts: "See the facts",
      bottleneck: "Name the bottleneck",
      plan: "Build the return plan",
      decision: "Choose this time",
    },
    stepState: {
      current: "Current",
      complete: "Done",
      upcoming: "Next",
    },
    stepHelp: {
      facts: "Look at the facts first. No self-judgment.",
      bottleneck: "Choose the main drag and define the smallest visible win.",
      plan: "Write WOOP, optional if-then, and the next 15-minute move.",
      decision: "Decide whether to keep going, detour, hold, or retreat.",
    },
    summaryLabels: {
      facts: "Mirror",
      bottleneck: "Smallest win",
      plan: "Next 15m",
      decision: "Decision",
    },
    fields: {
      mainQuest: "Main quest",
      quest: "Related quest",
      primaryBottleneck: "Primary bottleneck",
      diagnosisType: "Diagnosis type",
      avoidanceHypothesis: "Avoidance hypothesis",
      smallestWin: "Smallest visible win",
      woopPlan: "WOOP",
      woopPlaceholder: "Wish / Outcome / Obstacle / Plan",
      ifThenPlan: "If-then",
      ifThenPlaceholder: "If X happens, then I will do Y.",
      next15mAction: "Next 15-minute action",
      next15mPlaceholder: "What is the next small move?",
      decision: "Decision",
      reviewDate: "Review date",
      decisionNote: "Decision note",
      reason: "Reason",
      parkingNote: "Parking note",
      nextRestartStep: "Next restart step",
      resumeTriggerType: "Resume trigger type",
      resumeTriggerText: "Resume trigger",
    },
    buttons: {
      back: "Back",
      next: "Next",
      save: "Save return flow",
    },
    messages: {
      saved: "Return flow saved.",
    },
    labels: {
      next15m: "Next 15m",
      ifThen: "If-then",
    },
  },
} as const;

const ja = {
  nav: {
    portfolio: "ポートフォリオ",
    intake: "受け取り",
    map: "進め方",
    today: "今日",
    returnFlow: "戻し方",
    review: "ふり返り",
  },
  shell: {
    kicker: "Quest Agent v0.6",
    title: "進めつつ、止まったときの戻りコストを下げる",
    description: "本丸を一つに絞り、今日を軽く決め、勢いが落ちたら短く戻る",
    mirror: "いまの状況",
    focus: "本丸",
    nextRestart: "次の再開",
    portfolioHealth: "ポートフォリオ",
    healthTitle: "何を進めるか決め、ズレに気づいたら15分で戻る",
    activeGoals: "同時進行中",
    mainToday: "今日の本丸",
    switchDensity: "切替",
    activeGoalsPill: "進行中",
    localeLabel: "表示言語",
    languageJa: "日本語",
    languageEn: "English",
  },
  common: {
    openPortfolio: "ポートフォリオを開く",
    openToday: "今日を開く",
    openReturn: "戻し方を開く",
    openMap: "進め方を開く",
    cancel: "キャンセル",
    minutes: "分",
    running: "進行中",
    noSummary: "まだ概要がありません。",
    noData: "まだデータがありません。",
    backToToday: "今日に戻る",
  },
  today: {
    title: "今日を軽く決め、ズレたら短く戻る",
    lead: "Session Start は軽く、Mirror は事実だけ、Return は必要な時だけ使います。",
    noFocusTitle: "まだ本丸が選ばれていません。",
    noFocusBody: "まずはポートフォリオで本丸を一つ選んでください。",
    noRouteTitle: "この本丸にはまだ進め方がありません。",
    noRouteBody: "まずは進め方を作って、今日の 1 から 3 手に小さくしましょう。",
    replanAi: "AI で更新",
    replanHeuristic: "ルールで更新",
    openReturnHint: "本丸がまだ始まっていないのに改善やその他が続くときは、戻し方を開いてください。",
    mirrorTitle: "いまの状況",
    sessionStartTitle: "Session Start",
    sessionStartLead: "始める前に、つながり、成果物、時間、終わり方を決めます。",
    activeSessionTitle: "いまの作業",
    activeSessionEmpty: "Session Start から始めて、終わり方を先に決めましょう。",
    todayPlanTitle: "今日の進め方",
    sessionsTitle: "今日のセッション",
    sessionsEmpty: "最初の完了セッションが、比率や開始遅延の基準になります。",
    blockerTitle: "詰まりの記録",
    blockerLead: "責めずに、詰まっている点だけ書きます。",
    stats: {
      readyQuests: "動かしやすい作業",
      activeSession: "作業中",
      mainToday: "今日の本丸",
      metaToday: "メタ作業",
      switchDensity: "切替回数",
      returnState: "戻し方",
    },
    details: {
      readyQuests: "今日いちばん動かしやすい作業",
      noSession: "まだ作業中のセッションはありません",
      mainToday: "今日の本丸時間",
      metaToday: "回避寄りの改善 / その他",
      switchDensity: "ゴールと種別の切替",
      returnOpen: "戻した方がよさそう",
      returnClear: "このまま進めやすい",
    },
    fields: {
      category: "種別",
      quest: "作業",
      mainConnection: "本丸へのつながり",
      timebox: "時間制限",
      artifact: "今回外に出すもの",
      artifactPlaceholder: "メモ、送信済みメッセージ、決定、PR など",
      doneWhen: "終わり条件",
      doneWhenPlaceholder: "どこまで行けば終わるか",
      artifactLeft: "実際に残したもの",
      artifactLeftPlaceholder: "任意ですが、次回の再開が楽になります。",
      blockerTitle: "何が詰まっているか",
      blockerQuest: "関連作業",
      blockerDescription: "説明",
      blockerType: "種類",
      blockerSeverity: "重さ",
    },
    buttons: {
      runGate: "開始前チェック",
      confirmStart: "このセッションを始める",
      openReturnInstead: "先に戻し方を開く",
      finishSession: "セッションを終える",
      recordBlocker: "詰まりを記録する",
    },
    messages: {
      planAi: "AI が今日の進め方を更新しました。",
      planHeuristic: "ルールで今日の進め方を更新しました。",
      gateClear: "開始前チェックが終わりました。始めて大丈夫です。",
      gateRisk: "ズレの危険が見えます。先に戻し方を開くか、そのまま始めるか選べます。",
      sessionStartedBuild: "セッションを始めました。",
      sessionStartedAvoidant: "セッションを始めました。必要ならまだ戻し方を開けます。",
      sessionFinished: "セッションを終えました。",
      blockerSaved: "詰まりを記録しました。次の一手が見られます。",
    },
    labels: {
      doneWhen: "終わり条件",
      timebox: "時間制限",
      artifactLeft: "残したもの",
    },
  },
  portfolio: {
    title: "本丸を一つに保ち、並行作業を正直にする",
    lead: "本丸を前に置き、同時進行数を守り、保留にはきれいな再開メモを残します。",
    addGoal: "ゴールを追加",
    focusTitle: "いまの本丸",
    focusEmpty: "本丸はまだ選ばれていません",
    focusBody: "今週前に置くゴールを一つ選びましょう。",
    activeTitle: "進行中",
    activeEmpty: "まだ進行中のゴールはありません。",
    backlogTitle: "後ろに置くもの",
    backlogEmpty: "いまは後ろに置くゴールがありません。",
    parkedTitle: "保留中",
    parkedEmpty: "いまは保留中のゴールがありません。",
    resumeQueueTitle: "再開待ち",
    resumeQueueEmpty: "ゴールを保留すると、再開条件がここに出ます。",
    stats: {
      focusGoal: "本丸",
      activeGoals: "同時進行数",
      resumeQueue: "再開待ち",
      switches: "切替回数",
      medianResume: "再開まで",
      reviewRate: "ふり返り率",
    },
    details: {
      currentActiveCount: "いまの進行中数",
      resumeQueue: "再開メモ付きの保留ゴール",
      recordedThisWeek: "今週記録された数",
      restartDelay: "保留から再開まで",
      last4Weeks: "直近 4 週",
    },
    fields: {
      activeGoalLimit: "同時進行数",
      switchReason: "なぜいまこれを前に置くのか",
      switchReasonPlaceholder: "なぜこれを本丸にするのか",
      resumeReason: "なぜいま再開できるのか",
      resumeReasonPlaceholder: "なぜ今は再開して大丈夫か",
      stopMode: "止め方",
      resumeTrigger: "再開トリガー",
      whyStopNow: "なぜいま止めるか",
      parkingNote: "保留メモ",
      parkingNotePlaceholder: "どこまで進んだかと何が残っているか",
      nextRestartStep: "次に再開する一手",
      triggerDetail: "再開条件の詳細",
      triggerPlaceholder: "いつ戻すか、何がそろえば戻すか",
    },
    buttons: {
      saveLimit: "同時進行数を保存",
      editRoute: "進め方を開く",
      startIntake: "受け取りを始める",
      setFocus: "本丸にする",
      activateAndFocus: "動かして本丸にする",
      parkGoal: "保留する",
      resumeGoal: "再開する",
      saveParkingNote: "保留メモを保存",
    },
    queue: {
      missingGoal: "ゴールが見つかりません",
      parkedAgo: "{days} 日前に保留",
      whyStopped: "止めた理由",
      nextRestart: "次にやる最初の一手",
      trigger: "再開条件",
    },
    messages: {
      limitSaved: "同時進行数を更新しました。",
      focusSaved: "本丸を更新しました。",
      resumeSaved: "ゴールを再開しました。",
      parkedSaved: "ゴールを保留し、再開メモを残しました。",
    },
  },
  review: {
    title: "本丸への戻りやすさを、比率と遅延で見る",
    lead: "v0.6 では、今までの切替ふり返りに、本丸比率、メタ比率、開始遅延、再開遅延、切替回数、if-then 記入率を足しています。",
    noGoalTitle: "ふり返る前に、ゴールを一つ作ってください。",
    addGoal: "ゴールを追加",
    formTitle: "ふり返り入力",
    dailyLeadTitle: "日次指標",
    dailyLeadEmpty: "作業セッションと戻し方が記録されると、ここに指標が出ます。",
    focusCandidatesTitle: "次の本丸候補",
    focusCandidatesLead: "次に前に置くゴールはどれか",
    savedReviewsTitle: "保存済みのふり返り",
    savedReviewsEmpty: "最初のふり返りが、今後比べる基準になります。",
    stats: {
      mainRatio: "本丸比率",
      metaRatio: "メタ作業比率",
      startDelay: "本丸開始まで",
      resumeDelay: "再開まで",
      switchDensity: "切替回数",
      ifThen: "戻り方ルール記入率",
    },
    details: {
      mainRatio: "本丸時間 / 追跡時間",
      metaRatio: "回避寄りの改善 / その他",
      startDelay: "最初の作業から最初の本丸まで",
      resumeDelay: "保留から再開まで",
      switchDensity: "ゴールと種別の切替",
      ifThen: "Return で if-then が書かれた割合",
    },
    fields: {
      periodStart: "開始日",
      periodEnd: "終了日",
      summary: "進み具合のまとめ",
      learnings: "切替や再開で得た気づき",
      rerouteNote: "進め方の見直しメモ",
      nextFocus: "次の本丸",
    },
    buttons: {
      saveReview: "ふり返りを保存",
      setFocus: "本丸にする",
    },
    messages: {
      saved: "ふり返りを保存しました。",
      focusSaved: "ふり返りから本丸を更新しました。",
    },
    labels: {
      startDelay: "本丸開始まで",
      resumeDelay: "再開まで",
      switchDensity: "切替回数",
      ifThenCoverage: "戻り方ルール記入率",
      learnings: "気づき",
      reroute: "進め方メモ",
      nextFocus: "次の本丸",
    },
    candidateReason: "今週の本丸候補として整理しやすい",
  },
  returnFlow: {
    title: "ズレに気づき、一度だけ診断して、次の 15 分を決める",
    lead: "Mirror、COM-B、WOOP / if-then、判断までを 1 ページで短く進めます。",
    noFocusTitle: "まだ本丸が選ばれていません。",
    noFocusBody: "戻し方を使う前に、ポートフォリオで本丸を選んでください。",
    combTitle: "いまの詰まりを決める",
    planTitle: "戻り方を作る",
    decisionTitle: "今回の決め方",
    latestTitle: "直近の戻し方",
    steps: {
      facts: "事実を見る",
      bottleneck: "詰まりを決める",
      plan: "戻り方を作る",
      decision: "今回の決め方",
    },
    stepState: {
      current: "いまここ",
      complete: "完了",
      upcoming: "次",
    },
    stepHelp: {
      facts: "まずは事実だけを見ます。",
      bottleneck: "主な詰まりと、最小の勝ちを決めます。",
      plan: "WOOP、if-then、次の 15 分を書きます。",
      decision: "このまま進むか、変えるか、保留するか、撤退するかを決めます。",
    },
    summaryLabels: {
      facts: "Mirror",
      bottleneck: "最小の勝ち",
      plan: "次の 15 分",
      decision: "判断",
    },
    fields: {
      mainQuest: "本丸の作業",
      quest: "関連作業",
      primaryBottleneck: "主な詰まり",
      diagnosisType: "診断種別",
      avoidanceHypothesis: "回避仮説",
      smallestWin: "最小の勝ち",
      woopPlan: "WOOP",
      woopPlaceholder: "Wish / Outcome / Obstacle / Plan",
      ifThenPlan: "if-then",
      ifThenPlaceholder: "もし X なら、Y する",
      next15mAction: "次の 15 分でやること",
      next15mPlaceholder: "まずはどの一手か",
      decision: "判断",
      reviewDate: "見直し日",
      decisionNote: "補足メモ",
      reason: "理由",
      parkingNote: "保留メモ",
      nextRestartStep: "次に再開する一手",
      resumeTriggerType: "再開条件の種類",
      resumeTriggerText: "再開条件",
    },
    buttons: {
      back: "戻る",
      next: "次へ",
      save: "戻し方を保存",
    },
    messages: {
      saved: "戻し方を保存しました。",
    },
    labels: {
      next15m: "次の 15 分",
      ifThen: "if-then",
    },
  },
} as const;

const dictionaries = { ja, en } as const;
export type CopyDictionary = typeof en;

const labelMaps: Record<UiLocale, Record<string, string>> = {
  ja: {
    active: "進行中",
    planned: "予定",
    ready: "準備完了",
    suggested: "提案",
    in_progress: "進行中",
    completed: "完了",
    blocked: "詰まり",
    open: "未解決",
    resolved: "解消",
    high: "高",
    medium: "中",
    low: "低",
    draft: "下書き",
    paused: "一時停止",
    abandoned: "中止",
    hold: "保留",
    shrink: "縮小",
    cancel: "取りやめ",
    waiting: "再開待ち",
    resumed: "再開済み",
    manual: "手動",
    date: "日付",
    condition: "条件",
    heuristic: "ルール",
    ai: "AI",
    supabase: "Supabase",
    "local-file": "ローカル",
    "browser-local": "ブラウザ保存",
    main: "本丸",
    improve: "改善",
    admin: "事務",
    other: "その他",
    side: "サブ",
    direct: "直接",
    supporting: "支援",
    unclear: "不明",
    build: "本丸投資",
    avoidant: "回避寄り",
    fight: "このまま進む",
    detour: "少し変えて進む",
    retreat: "撤退",
    capability: "やり方",
    opportunity: "環境",
    motivation: "気力",
    clarity: "不明瞭",
    time: "時間",
    decision: "判断",
    dependency: "依存",
    energy: "エネルギー",
    unknown: "その他",
  },
  en: {
    active: "Active",
    planned: "Planned",
    ready: "Ready",
    suggested: "Suggested",
    in_progress: "In progress",
    completed: "Completed",
    blocked: "Blocked",
    open: "Open",
    resolved: "Resolved",
    high: "High",
    medium: "Medium",
    low: "Low",
    draft: "Draft",
    paused: "Paused",
    abandoned: "Abandoned",
    hold: "Hold",
    shrink: "Shrink",
    cancel: "Cancel",
    waiting: "Waiting",
    resumed: "Resumed",
    manual: "Manual",
    date: "Date",
    condition: "Condition",
    heuristic: "Heuristic",
    ai: "AI",
    supabase: "Supabase",
    "local-file": "Local file",
    "browser-local": "Browser local",
    main: "Main",
    improve: "Improve",
    admin: "Admin",
    other: "Other",
    side: "Side",
    direct: "Direct",
    supporting: "Supporting",
    unclear: "Unclear",
    build: "Build",
    avoidant: "Avoidant",
    fight: "Fight",
    detour: "Detour",
    retreat: "Retreat",
    capability: "Capability",
    opportunity: "Opportunity",
    motivation: "Motivation",
    clarity: "Clarity",
    time: "Time",
    decision: "Decision",
    dependency: "Dependency",
    energy: "Energy",
    unknown: "Unknown",
  },
};

export function getCopy(locale: UiLocale): CopyDictionary {
  return (dictionaries[locale] ?? dictionaries.ja) as CopyDictionary;
}

export function getLabel(locale: UiLocale, value: string): string {
  return labelMaps[locale]?.[value] ?? value.replace(/_/g, " ");
}

export function localizeRuntimeError(_locale: UiLocale, error: unknown, fallback: string): string {
  if (error instanceof Error && error.message.trim()) {
    return error.message;
  }
  if (typeof error === "string" && error.trim()) {
    return error;
  }
  return fallback;
}

export function interpolate(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, key) => String(values[key] ?? `{${key}}`));
}
